# Uncomment the next line to define a global platform for your project
 platform :ios, '9.3'

target 'AppArchitecture' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppArchitecture

  pod 'CwlSignal', :git => 'https://github.com/mattgallagher/CwlSignal.git'
  pod 'CwlUtils', :git => 'https://github.com/mattgallagher/CwlUtils.git'
  


end
